export const routeName = {
    SPLASH_SCREEN: '/',
    ONBOARDING: '/onboarding',
    PHONE_NUMBER_VERIFICATION: '/phone-number-verification',
    EMAIL_VERIFICATION: '/email-verification',
    LOCATION: '/location',
    SELECT_LOCATION: '/select-location',
    FETCH_LOCATION: '/fetch-location',
    HOME: '/home',
    ORDERS: '/orders',
    PROFILE: '/profile',
    RESTAURANT: '/restaurant',
    FOLLOWING: '/following',
    CHECKOUT: '/checkout',
    ORDERSTATUS: '/orderstatus',
    RATINGS: '/ratings',
    SEARCH: '/search',
    TERMSANDCONDITION: '/termsAndCondition',
    PRIVACYPOLICY: '/privacyPolicy',
    CONTACTUS: '/contactUs',
    EDITPROFILE: '/editProfile',
    SAVEDADDRESS: '/savedAddress',
    COUPONS: '/coupons',
    NOTFOUND: '/notfound'
}